[package]
name = "discord-rust-framework"
version = "0.0.1"
authors = ["Arjun Dhaliwal <arjun.p.dhaliwal@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
websocket = "0.20.2"
serde = "1.0.11"
serde_json = "1.0.2"
serde_derive = "1.0"
